spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url : jdbc:mysql://localhost:3306/greeneryonwheels
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa.show-sql: true

  logging:
    level:
      org:
        springframework:
          security: DEBUG



jwt:
  secret: MTIzNDU=